# Generated by Django 3.2.4 on 2021-06-16 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addannouncement",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
