# Generated by Django 3.2.4 on 2021-06-16 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_addannouncement_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
