# Generated by Django 3.2.6 on 2021-08-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_tournament"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="tournament_author",
            new_name="author",
        ),
    ]
