# Generated by Django 3.2.4 on 2021-06-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_addannouncement_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addannouncement',
            name='announcement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
