# Generated by Django 3.2.6 on 2021-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_tournament_author_tournament_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="tournament_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
