# Generated by Django 3.2.4 on 2021-06-16 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_addannouncement_announcement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="addannouncement",
            name="announcement_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
