# Generated by Django 3.2.4 on 2021-06-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_addannouncement_announcement_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="lessonDifficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
