# Generated by Django 3.2.4 on 2021-06-16 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_lessondifficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondifficulty",
            name="difficulty",
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
