# Generated by Django 3.2.4 on 2021-06-17 00:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_lessondifficulty_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='addLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('difficulty', models.CharField(default='Easy', max_length=225)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lesson_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
