# Generated by Django 3.2.4 on 2021-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_profile_pic",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
