# Generated by Django 3.2.6 on 2021-08-19 18:45

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=martor.models.MartorField(blank=True),
        ),
    ]
