# Generated by Django 3.2.6 on 2021-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userprofile_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_color',
            field=models.CharField(default='#aaa!important', max_length=225),
        ),
    ]
