# Generated by Django 3.2.4 on 2021-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210620_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_facebook_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
