name: Build

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Format with Black
        run: |
          black .
      - name: Lint with flake8
        run: |
          flake8 . --statistics --show-source --ignore=W503 --max-line-length=120
  build-docker:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start containers using docker compose
        run: |
          echo ${{ secrets.django_secret }} > .env
          docker-compose up --build -d
      - name: Stop containers
        if: always()
        run: docker-compose down --rmi all
