name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          pip install -r requirements.txt
      - name: Format with Black
        run: |
          black .
      - name: Lint with flake8
        run: |
          flake8 . --statistics --show-source --ignore=W503 --max-line-length=120
